{"name": "Переход в историю заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"7fe30d64-f4b3-427a-9593-c8d618c4cfbe\")>\nuser = {'email': 'millerdouglas@example.org', 'name': 'anthony00', 'password': '381681534'}\n\n    @pytest.fixture\n    def user_login(driver, user):\n        main_page = MainPage(driver)\n        main_page.click_on_personal_cabinet_button()\n        login_page = LoginPage(driver)\n        login_page.set_email(user['email'])\n        login_page.set_password(user['password'])\n        login_page.click_on_login_button()\n>       login_page.changing_url_login()\n\nconftest.py:50: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\login_page.py:31: in changing_url_login\n    return self.wait_changing_url(Urls.BASE_URL + Urls.LOGIN_URL)\npages\\base_page.py:24: in wait_changing_url\n    return WebDriverWait(self.driver, 20).until(expected_conditions.url_changes(url))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"7fe30d64-f4b3-427a-9593-c8d618c4cfbe\")>\nmethod = <function url_changes.<locals>._predicate at 0x00000230EDB5D3A0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nC:\\Users\\ilnazhim\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1719498294496, "stop": 1719498294496, "uuid": "963ff8af-42a0-4b86-b9d4-f1c3775c3801", "historyId": "d4085d4b82134b831c05ef8be7ebf5c9", "testCaseId": "18deedb9bd6c34095490849d2c36764c", "fullName": "tests.test_personal_account.TestPersonalAccount#test_order_history", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_personal_account"}, {"name": "subSuite", "value": "TestPersonalAccount"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "3044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_personal_account"}]}